apiVersion: v1
kind: Service
metadata:
  name: autodeploy-service
  labels:
    app: autodeploy
spec:
  type: LoadBalancer
  selector:
    app: autodeploy
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
